name: CI

on:
  pull_request:
    types: [opened, reopened]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo ${{ github.github.head_ref }}
