name: CI

on:
  pull_request:
    types: [opened, reopened]
    branches:    
      - 'main'
  
jobs:
  build:
    runs-on: ubuntu-latest
    # if: ${{ github.base_ref == 'main'}}
    steps:
      - uses: actions/checkout@v3
      
      - name: Run a multi-line script
        run: |
          echo ${{ github.base_ref }}
          echo ${{ github.head_ref }}
